/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseIcon: typeof import('./src/components/BaseIcon.vue')['default']
    Cell: typeof import('./src/components/Cell.vue')['default']
    CustomTabBar: typeof import('./src/components/CustomTabBar.vue')['default']
    Pill: typeof import('./src/components/Pill.vue')['default']
    VolumeBar: typeof import('./src/components/VolumeBar.vue')['default']
  }
}
